version: "3.4"
volumes:
  my-db:
networks:
  app-network:
    driver: bridge
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - my-db:/data/db
    networks:
      - app-network
  app:
    image: devblinq/prompt-server:latest
    environment:
      - MONGO_URI=mongodb://db:27017/promptsvr
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - app-network
    depends_on:
      - db
